### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [RustingRobot/Kea#18]
Hello, what about you make kea compatible for more sites. Maybe https://tapas.io/ and more! I know this is a bit random but I think it would be pretty cool if kea was multipurpose!

**Comment by pzkt** [comment]
I think kea should stay with only webtoons downloading because adding more supported websites would require more work and time that I'm not willing to invest into kea (since this is only a small project of mine and I want to keep it small :P )

If you would like to download comics from tapas I would suggest looking at [tachiyomi](https://github.com/tachiyomiorg/tachiyomi), an android app for downloading comics from all sorts of websites. Kea will concentrate on webtoons and I'll still maintain this project for the foreseeable future :)

**Comment by ghost** [comment]
alright, sorry for the late response
